### ISSUE TITLE
Why was WalletConnect removed?

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-tools/celo-web-wallet#125]
#### Feature Description

I was using WalletConnect to connect my ledger to dApps, because Ledger live does not let me connect on Celo network.

**Comment by jmrossy** [comment]
Hi @therealharpaljadeja,
It was temporarily removed because the version that Celo Wallet was using was outdated and no longer compatible with the version the broader ecosystem is using. It will be added back when WC support can be updated and fixed. Unfortunately I don't have time to work on that at the moment.

**Comment by 0xarthurxyz** [comment]
@therealharpaljadeja did you make any progress on doing this work?

**Comment by therealharpaljadeja** [comment]
[Celo Terminal](https://github.com/zviadm/celoterminal#celo-terminal) has WalletConnect v2 support and custom derivation path support works for me!
