### ISSUE TITLE
"Send" interface

### ISSUE THREAD

**Issue by ibmua** [celo-tools/celo-web-wallet#68]
In "send", please, make the coin sected more in-your-face and don't select any coin by default, because it's not a minor question which token is being sent. I accidentally sent 2k CUSD to Binance instead of Celo and Binance even denied my token retrieval application "Unfortunately, this unlisted token cannot be retrieved. Please take note of the token and network for your next transaction as we cannot guarantee that we are able to retrieve an unlisted token.". So I basically lost $2k because of the defaults of the wallet app.

If you think that cusd is good to have by default, please, imagine an ethereum wallet having this interface. Yes, I can't imagine that too. Most likely, there is no other wallet in the industry that has default coins. Definitely no such wallet with any user traction. For a GOOOOOD reason. This is, of course, related to smart contracts platforms. As for blockchains that only have a single coin, obviously, this is different.

**Comment by jmrossy** [comment]
@ibmua I'm sorry to hear you lost some funds. Don't forget about them because when Binance eventually starts listing cUSD they may be able to retrieve them for you.

The confirmation screen shows the token too but maybe it can be more obvious:
<img width="382" alt="Screen Shot 2021-09-13 at 10 39 52" src="https://user-images.githubusercontent.com/710751/133104843-4517ad13-ab2d-4f7c-abc8-a3126aafe090.png">

I'll either change the default to no token or make it CELO by default.

**Comment by ibmua** [comment]
Yeah, I hope Celo will eventually get some exclusive worthy projects on it’s blockchain and Binance will program a better support for Celo tokens. Little hope for cUSD, as it didn’t even list UST yet. If they made the thing self-serviceable via transferring their own recognized assets to their main wallet and handing over private keys that would be awesome.

Definitely make it a none by default. Celo as default means someone may transfer celo instead of cusd, that could be even worse. And current users may already expect cUSD to be selected by default. So definitely make token selection mandatory.

**Comment by jmrossy** [comment]
@ibmua Agreed, the next update will set the send token to none by default
